spring:
  datasource:
    url: jdbc:mysql://192.168.58.128:3306/test?characterEncoding=UTF-8
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect